-- Reset (Drop existing tables to start clean)
drop table if exists public.participants cascade;
drop table if exists public.draws cascade;

-- 1. Create draws table (without foreign key to participants yet)
create table public.draws (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  draw_date date not null default current_date,
  status text check (status in ('pending', 'completed')) default 'pending',
  winning_participant_id bigint, -- FK added later
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create participants table
create table public.participants (
  id bigint generated by default as identity primary key,
  draw_id uuid references public.draws(id) on delete cascade not null,
  user_id text,
  name text,
  extra_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Add circular foreign key to draws
alter table public.draws 
  add constraint fk_winner 
  foreign key (winning_participant_id) 
  references public.participants(id);

-- 4. Enable RLS
alter table public.draws enable row level security;
alter table public.participants enable row level security;

-- 5. Policies
create policy "Enable read access for all users" on public.draws for select using (true);
create policy "Enable insert for authenticated users only" on public.draws for insert with check (true);
create policy "Enable update for authenticated users only" on public.draws for update using (true);

create policy "Enable read access for all users" on public.participants for select using (true);
create policy "Enable insert for authenticated users only" on public.participants for insert with check (true);
